package cliui

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ceoai/navi/internal/connectors"
	"github.com/charmbracelet/huh"
)

// DisplayPassport renders the owner passport using cliui BoxStyle instead of raw ASCII art.
func DisplayPassport(ownerName, instanceID, secretFP, ownerSecret, apiKey, recoverySeed string) {
	fmt.Println()
	fmt.Println(TitleStyle.Render("Owner Passport"))

	var lines []string
	lines = append(lines, fmt.Sprintf("Owner:       %s", ownerName))
	lines = append(lines, fmt.Sprintf("Instance ID: %s", instanceID))
	lines = append(lines, fmt.Sprintf("Secret FP:   %s", secretFP))
	lines = append(lines, "")
	if ownerSecret != "" {
		lines = append(lines, fmt.Sprintf("Owner Secret: %s", ownerSecret))
	}
	lines = append(lines, fmt.Sprintf("API Key:     %s", apiKey))
	lines = append(lines, fmt.Sprintf("Recovery:    %s", recoverySeed))
	lines = append(lines, "")
	lines = append(lines, DimStyle.Render("Store your owner secret and recovery seed safely."))
	lines = append(lines, DimStyle.Render("Use the API key for normal access."))
	lines = append(lines, DimStyle.Render("Reserve your owner secret for recovery only."))

	fmt.Println(BoxStyle.Render(strings.Join(lines, "\n")))
	fmt.Println()
}

// RunPassportSave prompts the user to optionally save their passport to a file.
// The file is written as plain text (no ANSI codes) with mode 0600.
// Call this immediately after DisplayPassport.
func RunPassportSave(ownerName, instanceID, secretFP, ownerSecret, apiKey, recoverySeed string) error {
	var save bool
	confirmForm := huh.NewForm(
		huh.NewGroup(
			Confirm(
				"Save passport to a file?",
				"Saves your credentials as plain text so you can store them securely.",
				&save,
			),
		),
	)
	if err := confirmForm.Run(); err != nil {
		return err
	}
	if !save {
		return nil
	}

	defaultPath := "navi-passport.txt"
	if home, err := os.UserHomeDir(); err == nil {
		defaultPath = filepath.Join(home, "navi-passport.txt")
	}

	var destPath string
	pathForm := huh.NewForm(
		huh.NewGroup(
			Input(
				"Save to",
				"Full path for the passport file.",
				defaultPath,
				&destPath,
			),
		),
	)
	if err := pathForm.Run(); err != nil {
		return err
	}
	if destPath == "" {
		destPath = defaultPath
	}

	content := strings.Join([]string{
		"NAVI Owner Passport",
		strings.Repeat("=", 40),
		fmt.Sprintf("Owner:       %s", ownerName),
		fmt.Sprintf("Instance ID: %s", instanceID),
		fmt.Sprintf("Secret FP:   %s", secretFP),
		"",
		fmt.Sprintf("Owner Secret: %s", ownerSecret),
		fmt.Sprintf("API Key:     %s", apiKey),
		fmt.Sprintf("Recovery:    %s", recoverySeed),
		"",
		"Store this file in a secure location.",
		"Use the API key for normal access.",
		"Reserve your recovery seed for account recovery only.",
	}, "\n") + "\n"

	if err := os.WriteFile(destPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to save passport: %w", err)
	}

	fmt.Println(SuccessStyle.Render(fmt.Sprintf("Passport saved to %s", destPath)))
	fmt.Println()
	return nil
}

// RunPassportConfirmation shows the recovery seed and requires the user to confirm they have stored it.
// This must be called after the claim API call since the server generates the seed.
func RunPassportConfirmation(recoverySeed string) error {
	fmt.Println(TitleStyle.Render("Recovery Seed"))

	seedBox := BoxStyle.Render(
		"Recovery Seed:\n\n" +
			"  " + recoverySeed + "\n\n" +
			DimStyle.Render("Write this down. You cannot recover it later."),
	)
	fmt.Println(seedBox)
	fmt.Println()

	var confirmed bool
	form := huh.NewForm(
		huh.NewGroup(
			Confirm(
				"Have you stored your recovery seed safely?",
				"You will not be able to retrieve this seed again.",
				&confirmed,
			),
		),
	)
	if err := form.Run(); err != nil {
		return err
	}
	if !confirmed {
		fmt.Println(DimStyle.Render("Continuing without confirmation. Make sure to save your recovery seed."))
	}
	return nil
}

// RunOnboardingFlow orchestrates the full sequence of onboarding forms.
func RunOnboardingFlow(gatewayURL string, apiKey string) (*OnboardingState, error) {
	ClearScreen()
	state := NewOnboardingState()

	// 1. Welcome
	if err := WelcomeForm(state).Run(); err != nil {
		return nil, err
	}
	if !state.BeginSetup {
		return nil, fmt.Errorf("onboarding cancelled")
	}

	// 2. Owner Name
	if err := OwnerForm(state).Run(); err != nil {
		return nil, err
	}

	// 3. Owner Recovery Secret mode (ONB-03 + ONB-04A/04B)
	if err := OwnerSecretModeForm(state).Run(); err != nil {
		return nil, err
	}
	if !state.UseAutoGeneratedOwnerSecret {
		if err := OwnerSecretManualForm(state).Run(); err != nil {
			return nil, err
		}
	} else {
		if err := OwnerSecretAutoConfirmForm(state).Run(); err != nil {
			return nil, err
		}
	}

	// 4. Provider & Model (ONB-07/ONB-08)
	catalog, err := FetchCatalog(gatewayURL, apiKey)

	// We always show the selection form now, because models.go includes defaults
	if err := ProviderSelectForm(catalog, state).Run(); err != nil {
		return nil, err
	}

	// If the user selected 'manual' from the catalog picker or we were forced into manual mode by the catalog failure
	if state.SelectedProvider == "manual" {
		if err := ManualProviderForm(state).Run(); err != nil {
			return nil, err
		}
	}

	if state.SelectedProvider != "skip" {
		// Ollama: discover locally installed models via `ollama list`
		if state.SelectedProvider == "ollama" {
			ollamaModels, ollamaErr := FetchOllamaModels()
			if ollamaErr == nil && len(ollamaModels) > 0 {
				if err := OllamaModelSelectForm(ollamaModels, state).Run(); err != nil {
					return nil, err
				}
			} else {
				// ollama not reachable or no models installed — fall through to manual
				if ollamaErr != nil {
					fmt.Println(DimStyle.Render("Could not reach `ollama list` — enter a model name manually."))
				} else {
					fmt.Println(DimStyle.Render("No Ollama models found — enter a model name manually."))
				}
			}
		} else if state.SelectedProvider != "manual" && err == nil {
			// Try to use catalog for models if we have it and the provider is known
			mf := ModelSelectForm(catalog, state)
			if mf != nil {
				if err := mf.Run(); err != nil {
					return nil, err
				}
			}
		}

		// Prompt for manual model if necessary
		if state.SelectedModel == "custom" || state.SelectedModel == "" {
			if err := ManualModelForm(state).Run(); err != nil {
				return nil, err
			}
		}

		// Prompt for API key
		kf := ProviderAPIKeyForm(state)
		if kf != nil {
			if err := kf.Run(); err != nil {
				return nil, err
			}
		}
	}

	// 5. Connector (ONB-09/ONB-10)
	schema, schemaErr := FetchSetupSchema(gatewayURL, apiKey)
	if schemaErr != nil {
		fmt.Println()
		fmt.Println(DimStyle.Render("Gateway not reachable — using built-in connector list."))
		fmt.Println()
		schema = connectors.BuiltinSetupDescriptors()
	}

	if err := ConnectorSelectForm(schema, state).Run(); err != nil {
		return nil, err
	}

	if state.SelectedConnector != "none" {
		paramsForm, cFields := BuildConnectorParamsForm(schema, state)
		if paramsForm != nil {
			if err := paramsForm.Run(); err != nil {
				return nil, err
			}
			// Sync back from temporary binding fields to state map
			for _, cf := range cFields {
				state.ConnectorParams[cf.Key] = cf.Value
				if cf.Label != "" {
					state.ConnectorParamLabels[cf.Key] = cf.Label
				}
			}
		}
	}

	// 6. Review (ONB-11)
	action, err := RunReviewScreen(state)
	if err != nil {
		return nil, err
	}
	switch action {
	case ReviewCancel:
		return nil, fmt.Errorf("onboarding cancelled")
	case ReviewGoBack:
		return nil, fmt.Errorf("onboarding cancelled at review")
	}

	return state, nil
}

// ReviewAction represents the user's choice at the ONB-11 review screen.
type ReviewAction string

const (
	ReviewConfirm ReviewAction = "confirm"
	ReviewGoBack  ReviewAction = "back"
	ReviewCancel  ReviewAction = "cancel"
)

// RunReviewScreen shows a summary of collected settings and returns the user's action.
// Secrets are redacted. Empty optional values are omitted.
func RunReviewScreen(state *OnboardingState) (ReviewAction, error) {
	fmt.Println()
	fmt.Println(TitleStyle.Render("Review your NAVI setup."))
	fmt.Println(DimStyle.Render("Confirm your configuration before NAVI applies it."))
	fmt.Println()

	var lines []string
	lines = append(lines, fmt.Sprintf("Owner:     %s", state.OwnerName))

	providerDisplay := state.SelectedProvider
	if providerDisplay == "" || providerDisplay == "skip" {
		providerDisplay = "(not configured)"
	}
	lines = append(lines, fmt.Sprintf("Provider:  %s", providerDisplay))

	if state.SelectedModel != "" {
		lines = append(lines, fmt.Sprintf("Model:     %s", state.SelectedModel))
	}

	connectorDisplay := state.SelectedConnector
	if connectorDisplay == "none" || connectorDisplay == "" {
		connectorDisplay = "None"
	}
	lines = append(lines, fmt.Sprintf("Connector: %s", connectorDisplay))

	if len(state.ConnectorParams) > 0 {
		lines = append(lines, "")
		lines = append(lines, "Connector Parameters:")
		for k, v := range state.ConnectorParams {
			if v == "" {
				continue // omit empty optional fields
			}
			displayKey := k
			if label, ok := state.ConnectorParamLabels[k]; ok && label != "" {
				displayKey = label
			}
			displayVal := v
			if strings.Contains(strings.ToLower(k), "token") || strings.Contains(strings.ToLower(k), "secret") || strings.Contains(strings.ToLower(k), "key") {
				displayVal = MaskSecret(v)
			}
			lines = append(lines, fmt.Sprintf("  %s: %s", displayKey, displayVal))
		}
	}

	fmt.Println(BoxStyle.Render(strings.Join(lines, "\n")))
	fmt.Println()

	var action string
	actionForm := huh.NewForm(
		huh.NewGroup(
			Select(
				"Review your NAVI setup.",
				"Choose an action to proceed.",
				[]huh.Option[string]{
					huh.NewOption("Confirm and apply", string(ReviewConfirm)),
					huh.NewOption("Go back", string(ReviewGoBack)),
					huh.NewOption("Cancel setup", string(ReviewCancel)),
				},
				&action,
			),
		),
	)
	if err := actionForm.Run(); err != nil {
		return ReviewCancel, err
	}
	return ReviewAction(action), nil
}

// RunApplyScreen shows the ONB-12 apply confirmation before committing any changes.
// Returns true if the user chose Apply, false if Cancel.
func RunApplyScreen() (bool, error) {
	fmt.Println()
	fmt.Println(TitleStyle.Render("Apply this configuration?"))
	fmt.Println(DimStyle.Render("NAVI will now save the setup and initialize required systems."))
	fmt.Println()

	var apply bool
	form := huh.NewForm(
		huh.NewGroup(
			Confirm(
				"Apply this configuration?",
				"NAVI will save your setup and activate all configured systems.",
				&apply,
			),
		),
	)
	if err := form.Run(); err != nil {
		return false, err
	}
	return apply, nil
}

// DisplayInitializing prints the ONB-13 initializing status message.
func DisplayInitializing() {
	fmt.Println()
	fmt.Println(TitleStyle.Render("Initializing NAVI..."))
	fmt.Println(DimStyle.Render("NAVI is activating the selected provider and any configured integrations."))
	fmt.Println()
}

// DisplayReady prints the ONB-14 ready state message.
// Must only be called after all apply/init calls have actually succeeded.
func DisplayReady(ownerName string) {
	fmt.Println()
	fmt.Println(TitleStyle.Render("NAVI is ready."))
	fmt.Println(DimStyle.Render(fmt.Sprintf("Setup is complete. Welcome, %s.", ownerName)))
	fmt.Println()
}

// GetSummaryTable is a helper for Task 5/Task 6 compatibility if needed,
// though RunReviewScreen now handles the display.
func GetSummaryTable(ownerName, provider, model, connector string, params map[string]string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("Owner: %s\n", ownerName))
	sb.WriteString(fmt.Sprintf("Provider: %s\n", provider))
	sb.WriteString(fmt.Sprintf("Model: %s\n", model))
	sb.WriteString(fmt.Sprintf("Connector: %s\n", connector))
	for k, v := range params {
		sb.WriteString(fmt.Sprintf("  %s: %s\n", k, MaskSecret(v)))
	}
	return sb.String()
}
