package cliui

// PassportData holds the server-generated owner identity returned from the claim API.
// It is populated mid-flow after the claim call and stored on OnboardingState.
type PassportData struct {
	OwnerName              string
	InstanceID             string
	OwnerSecretFingerprint string
	PrimaryAPIKey          string
	RecoverySeed           string
}

// OnboardingState preserves the user's progress through the onboarding flow.
type OnboardingState struct {
	BeginSetup                  bool
	OwnerName                   string
	OwnerSecret                 string
	UseAutoGeneratedOwnerSecret bool
	RecoveryConfirmed           bool
	SelectedProvider            string
	ProviderAPIKey              string
	SelectedModel               string
	SelectedConnector           string
	ConnectorParams             map[string]string
	// ConnectorParamLabels maps param key → human-readable label for display in review screens.
	ConnectorParamLabels map[string]string
	// Passport is populated mid-flow after the claim API call succeeds.
	Passport *PassportData
}

// NewOnboardingState initializes a fresh state.
func NewOnboardingState() *OnboardingState {
	return &OnboardingState{
		ConnectorParams:      make(map[string]string),
		ConnectorParamLabels: make(map[string]string),
	}
}
