package cliui

import (
	"fmt"

	"github.com/charmbracelet/huh"
)

// WelcomeForm returns the ONB-01 welcome/begin-setup confirmation form.
func WelcomeForm(state *OnboardingState) *huh.Form {
	return huh.NewForm(
		huh.NewGroup(
			Confirm(
				"Would you like to begin setting up NAVI?",
				"The first person to complete setup becomes this NAVI instance's owner.",
				&state.BeginSetup,
			),
		),
	)
}

// OwnerForm returns the ONB-02 form for capturing the owner name only.
func OwnerForm(state *OnboardingState) *huh.Form {
	return huh.NewForm(
		huh.NewGroup(
			Input(
				"What should NAVI call you?",
				"This name is used to establish initial ownership of the instance.",
				"Your name",
				&state.OwnerName,
			).(*huh.Input).
				Validate(func(s string) error {
					if len(s) == 0 {
						return fmt.Errorf("owner name is required")
					}
					return nil
				}),
		),
	)
}

// OwnerSecretModeForm returns the ONB-03 form for selecting secret generation mode.
// It sets UseAutoGeneratedOwnerSecret on the state.
func OwnerSecretModeForm(state *OnboardingState) Runner {
	// Bind to a local string and sync back to state.UseAutoGeneratedOwnerSecret.
	// We use a pointer trick via a side-effecting select.
	var mode string
	if state.UseAutoGeneratedOwnerSecret {
		mode = "generate"
	} else {
		mode = "generate" // default to generate
	}

	form := huh.NewForm(
		huh.NewGroup(
			Select(
				"How would you like to set your owner recovery secret?",
				"This is a break-glass credential used only for recovery and high-level administrative access.",
				[]huh.Option[string]{
					huh.NewOption("Generate one for me", "generate"),
					huh.NewOption("Enter one manually", "manual"),
				},
				&mode,
			),
		),
	)

	return &secretModeForm{Form: form, mode: &mode, state: state}
}

// secretModeForm wraps huh.Form to sync the mode selection back to state after Run.
type secretModeForm struct {
	*huh.Form
	mode  *string
	state *OnboardingState
}

func (f *secretModeForm) Run() error {
	if err := f.Form.Run(); err != nil {
		return err
	}
	f.state.UseAutoGeneratedOwnerSecret = (*f.mode == "generate")
	return nil
}

// OwnerSecretAutoConfirmForm returns the ONB-04A informational confirm for auto-generation.
func OwnerSecretAutoConfirmForm(state *OnboardingState) *huh.Form {
	var ok bool
	return huh.NewForm(
		huh.NewGroup(
			Confirm(
				"Your owner recovery secret will be generated automatically.",
				"NAVI will create a secure owner recovery secret for this instance.",
				&ok,
			),
		),
	)
}

// OwnerSecretManualForm returns the ONB-04B masked secret input for manual entry.
func OwnerSecretManualForm(state *OnboardingState) *huh.Form {
	return huh.NewForm(
		huh.NewGroup(
			Secret(
				"Enter your owner recovery secret.",
				"Choose a strong secret and store it safely.",
				"Secret passphrase",
				&state.OwnerSecret,
			).(*huh.Input).
				Validate(func(s string) error {
					if len(s) == 0 {
						return fmt.Errorf("owner recovery secret is required")
					}
					return nil
				}),
		),
	)
}
