package navi

const (
	inferenceScratchDecisionEnvelope    = "ics.decision_envelope"
	inferenceScratchVersion             = "ics.version"
	inferenceScratchGoalStack           = "ics.goal_stack"
	inferenceScratchFocusID             = "ics.focus_id"
	inferenceScratchGoalID              = "ics.goal_id"
	inferenceScratchFocusReason         = "ics.focus_reason"
	inferenceScratchDominantMode        = "ics.dominant_mode"
	inferenceScratchSubmodeChain        = "ics.submode_chain"
	inferenceScratchCandidateID         = "ics.candidate_id"
	inferenceScratchCandidateType       = "ics.candidate_type"
	inferenceScratchGovernanceOutcome   = "ics.governance_outcome"
	inferenceScratchGovernanceCommand   = "ics.governance.command_type"
	inferenceScratchGovernanceDomain    = "ics.governance.domain"
	inferenceScratchGovernanceTags      = "ics.governance.tags"
	inferenceScratchGovernanceHandoff   = "ics.governance.handoff"
	inferenceScratchDecisionTraceID     = "ics.trace_id"
	inferenceScratchIntentActionType    = "ics.intent.action_type"
	inferenceScratchIntentTarget        = "ics.intent.target"
	inferenceScratchExecutionIntent     = "ics.execution_intent"
	inferenceScratchApprovalRequirement = "ics.approval_requirement"
	inferenceScratchTargetCapability    = "ics.target_capability"
	inferenceScratchAllowedCapabilities = "ics.allowed_capabilities"
	inferenceScratchRecoveryCheckpoint  = "ics.recovery_checkpoint_ref"
	inferenceScratchRecoveryRoute       = "ics.recovery_route"
	inferenceScratchReflectionTrigger   = "ics.reflection_trigger"
	inferenceScratchPostureState        = "ics.posture_state"
	inferenceScratchArbitrationState    = "ics.arbitration_state"
	inferenceScratchFocusStartedAt      = "ics.focus_started_at"
	inferenceScratchPlanID              = "ics.plan_id"
	inferenceScratchPlanStatus          = "ics.plan_status"
	inferenceScratchPlanCurrentNode     = "ics.plan_current_node"
	inferenceScratchPlanGraph           = "ics.plan_graph"
	inferenceScratchLastResult          = "ics.last_result"
)
