# Code generated by schema/python/gen — DO NOT EDIT.
#
# Source: canonical Go governed types in internal/schema, internal/governor,
# internal/connectors. Regenerate with `make generate-python`.
#
# Stdlib-only: dataclasses + enum, no third-party dependencies. Enum values are
# read from Go source and struct shapes from Go reflection, so this module never
# drifts from the kernel (Language-Layer Contract §7: generated, not hand-written).
"""Governed type contracts for NAVI (Go → Python). Stdlib-only."""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum, IntEnum
from typing import Any, Dict, List, Optional

__all__ = [
    "ActionDescriptor",
    "AgentType",
    "ApprovalOutcome",
    "AssistantMessageCompletedPayload",
    "AssistantMessageKind",
    "AssistantMessagePartialPayload",
    "AssistantTokenDeltaPayload",
    "CapabilityDescriptor",
    "CommandType",
    "CompensationStatus",
    "ComposeFailureMode",
    "ContentTrust",
    "ContextReadAuditPayload",
    "DegradationNotedPayload",
    "DegradationVisibility",
    "Event",
    "EventEnvelope",
    "EventKind",
    "EventType",
    "EventVisibility",
    "ExecutionOutcome",
    "ExecutionOutcomeOutcome",
    "FailureClass",
    "GovernanceBlockedPayload",
    "GovernanceTier",
    "IdempotencyExpectation",
    "InferenceDecisionTracePayload",
    "IntakeRecordRef",
    "InterruptAppliedPayload",
    "InterruptRaisedPayload",
    "JobMode",
    "MessageClassifiedPayload",
    "MessageQueueActionPayload",
    "MessageReceivedPayload",
    "MutationDescriptor",
    "MutationKind",
    "PrivacyClass",
    "Proposal",
    "ProposalPriority",
    "ProposalResolvedPayload",
    "ProposalStatus",
    "ProposalWaitingPayload",
    "RecoveryRequiredPayload",
    "RecoveryStatus",
    "ResolutionResult",
    "ResolutionType",
    "ResultEnvelope",
    "ReversibilityClass",
    "RunCancelledPayload",
    "RunCompletedPayload",
    "RunFailedPayload",
    "RunPausedPayload",
    "RunPhaseChangedPayload",
    "RunResumedPayload",
    "RunStartedPayload",
    "RunStatus",
    "SoftenedMutation",
    "ToolCallCompletedPayload",
    "ToolCallFailedPayload",
    "ToolCallProgressPayload",
    "ToolCallStartedPayload",
    "ValidationOutcome",
    "ValidationResult",
]


class AgentType(str, Enum):
    AGENT_NAVI = "navi"
    AGENT_HEARTBEAT = "heartbeat"
    AGENT_CONNECTOR = "connector"
    AGENT_CODER = "coder"
    AGENT_CRITIC = "critic"
    AGENT_STRATEGIST = "strategist"
    AGENT_SCOUT = "scout"


class ApprovalOutcome(str, Enum):
    NA = "na"
    DENIED = "denied"
    ALLOW_ONCE = "allow_once"
    ALWAYS_ALLOW = "always_allow"
    SWITCHED_WORKSPACE = "switched_workspace"


class AssistantMessageKind(str, Enum):
    REPLY = "reply"
    PROACTIVE = "proactive"


class CommandType(str, Enum):
    QUERY = "query"
    CREATE = "create"
    UPDATE = "update"
    DELETE = "delete"
    INVOKE = "invoke"
    SEND = "send"
    ACQUIRE = "acquire"
    SCHEDULE = "schedule"
    DELEGATE = "delegate"
    COMPOSE = "compose"


class CompensationStatus(str, Enum):
    NOT_REQUIRED = "not_required"
    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"
    NOT_POSSIBLE = "not_possible"


class ComposeFailureMode(str, Enum):
    COMPOSE_FAILURE_ROLLBACK = "rollback"
    COMPOSE_FAILURE_COMPENSATION = "compensation"
    COMPOSE_FAILURE_SURFACE_PARTIAL = "surface_partial"


class ContentTrust(str, Enum):
    OWNER = "owner"
    INTERNAL_SYSTEM = "internal_system"
    TRUSTED_PLUGIN = "trusted_plugin"
    EXTERNAL_UNTRUSTED = "external_untrusted"


class DegradationVisibility(str, Enum):
    DEGRADATION_SILENT_RETRY = "silent_retry"
    DEGRADATION_ADVISORY = "advisory"
    DEGRADATION_BLOCKING = "blocking"
    DEGRADATION_DEFERRED_RECOVERY = "deferred_recovery"


class EventKind(str, Enum):
    COMMAND = "command"
    FACT = "fact"


class EventType(str, Enum):
    CMD_AGENT_REGISTER = "cmd.agent.register"
    CMD_AGENT_RETIRE = "cmd.agent.retire"
    FACT_DIRECTIVE_REPLIED = "fact.directive.replied"
    CMD_DIRECTIVE_MESSAGE = "cmd.directive.message"
    CMD_TASK_ASSIGN = "cmd.task.assign"
    FACT_COST_RECORDED = "fact.cost.recorded"
    FACT_GOVERNOR_TRIPPED = "fact.governor.tripped"
    FACT_AGENT_BUDGET_EXCEEDED = "fact.agent.budget.exceeded"
    FACT_NAVI_REPLIED = "navi.fact.replied"
    FACT_NAVI_REPLY_CHUNK = "navi.fact.reply.chunk"
    FACT_NAVI_EXPERIENCE_MODE_CHANGED = "navi.fact.experience_mode_changed"
    FACT_NAVI_EXPERIENCE_SNAPSHOT = "navi.fact.experience_snapshot"
    FACT_NAVI_SKILL_LOADED = "navi.fact.skill_loaded"
    FACT_NAVI_SKILL_ERROR = "navi.fact.skill_error"
    FACT_NAVI_HEARTBEAT_DONE = "navi.fact.heartbeat_done"
    FACT_NAVI_ACTION_REQUESTED = "navi.fact.action_requested"
    FACT_REFLECTION_QUEUED = "navi.fact.reflection_queued"
    FACT_SUBCONSCIOUS_INTERRUPTION = "navi.fact.subconscious_interruption"
    FACT_RUN_STARTED = "run.started"
    FACT_RUN_PHASE_CHANGED = "run.phase.changed"
    FACT_INFERENCE_DECISION_TRACE = "inference.decision.trace"
    FACT_RUN_PAUSED = "run.paused"
    FACT_RUN_RESUMED = "run.resumed"
    FACT_RUN_COMPLETED = "run.completed"
    FACT_RUN_FAILED = "run.failed"
    FACT_RUN_CANCELLED = "run.cancelled"
    FACT_INTERRUPT_RAISED = "interrupt.raised"
    FACT_INTERRUPT_APPLIED = "interrupt.applied"
    FACT_TOOL_CALL_STARTED = "tool.call.started"
    FACT_TOOL_CALL_PROGRESS = "tool.call.progress"
    FACT_TOOL_CALL_COMPLETED = "tool.call.completed"
    FACT_TOOL_CALL_FAILED = "tool.call.failed"
    FACT_MESSAGE_RECEIVED = "message.received"
    FACT_MESSAGE_CLASSIFIED = "message.classified"
    FACT_MESSAGE_MERGED = "message.merged"
    FACT_MESSAGE_DEFERRED = "message.deferred"
    FACT_MESSAGE_SUPERSEDED = "message.superseded"
    FACT_ASSISTANT_TOKEN_DELTA = "assistant.token.delta"
    FACT_ASSISTANT_MESSAGE_PARTIAL = "assistant.message.partial"
    FACT_ASSISTANT_MESSAGE_COMPLETED = "assistant.message.completed"
    FACT_CONTEXT_READ = "context.read"
    FACT_GOVERNANCE_BLOCKED = "governance.blocked"
    FACT_PROPOSAL_WAITING = "proposal.waiting"
    FACT_PROPOSAL_RESOLVED = "proposal.resolved"
    FACT_DEGRADATION_NOTED = "degradation.noted"
    FACT_RECOVERY_REQUIRED = "recovery.required"
    FACT_ARTIFACT_CREATED = "artifact.created"
    FACT_ARTIFACT_UPDATED = "artifact.updated"
    FACT_ARTIFACT_ARCHIVED = "artifact.archived"
    FACT_ARTIFACT_RESTORED = "artifact.restored"
    FACT_ARTIFACT_BRANCHED = "artifact.branched"
    FACT_ARTIFACT_DELETED = "artifact.deleted"
    FACT_ARTIFACT_VERSION_COMMITTED = "artifact.version.committed"
    FACT_ARTIFACT_VERSION_RESTORE_REQUESTED = "artifact.version.restore_requested"
    FACT_ARTIFACT_LIFECYCLE_CHANGED = "artifact.lifecycle.changed"
    FACT_ARTIFACT_EXECUTION_STARTED = "artifact.execution.started"
    FACT_ARTIFACT_EXECUTION_COMPLETED = "artifact.execution.completed"
    FACT_ARTIFACT_EXECUTION_FAILED = "artifact.execution.failed"
    FACT_ARTIFACT_PATCH_FAILED = "artifact.patch.failed"
    FACT_ARTIFACT_RENDERER_RESOLVED = "artifact.renderer.resolved"
    FACT_ARTIFACT_RENDERER_MISSING = "artifact.renderer.missing"
    FACT_ARTIFACT_WORKSPACE_LOADED = "artifact.workspace.loaded"
    FACT_ARTIFACT_WORKSPACE_LOAD_FAILED = "artifact.workspace.load_failed"
    FACT_ARTIFACT_EXPORT_COMPLETED = "artifact.export.completed"
    FACT_ARTIFACT_SYNC_COMPLETED = "artifact.sync.completed"
    FACT_ARTIFACT_SYNC_FAILED = "artifact.sync.failed"
    FACT_ARTIFACT_CONFLICT_DETECTED = "artifact.conflict.detected"
    FACT_ARTIFACT_MATERIALIZED = "artifact.materialized"


class EventVisibility(str, Enum):
    VISIBILITY_USER = "user_visible"
    VISIBILITY_OPERATOR = "operator_visible"
    VISIBILITY_AUDIT = "audit_only"


class ExecutionOutcomeOutcome(str, Enum):
    EXECUTION_OUTCOME_SUCCEEDED = "succeeded"
    EXECUTION_OUTCOME_FAILED = "failed"
    EXECUTION_OUTCOME_PARTIALLY_SUCCEEDED = "partially_succeeded"
    EXECUTION_OUTCOME_CANCELLED = "cancelled"
    EXECUTION_OUTCOME_TIMED_OUT = "timed_out"
    EXECUTION_OUTCOME_REJECTED_PRE_EXECUTION = "rejected_pre_execution"


class FailureClass(str, Enum):
    VALIDATION_REJECTION = "validation_rejection"
    PERMISSION_DENIAL = "permission_denial"
    POLICY_BLOCKED = "policy_blocked"
    APPROVAL_PENDING = "approval_pending"
    VERSION_CONFLICT = "version_conflict"
    RENDERER_MISSING = "renderer_missing"
    PATCH_APPLY_FAILED = "patch_apply_failed"
    SCHEMA_INVALID = "schema_invalid"
    SANDBOX_BLOCKED = "sandbox_blocked"
    STORAGE_FAILURE = "storage_failure"
    EXPORT_FAILURE = "export_failure"
    SYNC_FAILURE = "sync_failure"
    UNKNOWN = "unknown"
    CONNECTOR_UNAVAILABLE = "connector_unavailable"
    EXECUTION_FAILURE = "execution_failure"
    PARTIAL_EXECUTION = "partial_execution"
    TIMEOUT = "timeout"
    PLUGIN_CRASH = "plugin_crash"
    CONTRADICTION_STALE_STATE = "contradiction_stale_state"


class GovernanceTier(str, Enum):
    SYSTEM = "system"
    OWNER = "owner"
    PLUGIN = "plugin"


class IdempotencyExpectation(str, Enum):
    IDEMPOTENCY_IDEMPOTENT = "idempotent"
    IDEMPOTENCY_NOT_IDEMPOTENT = "not_idempotent"
    IDEMPOTENCY_VERSION_AWARE = "version_aware"
    IDEMPOTENCY_DEPENDS_ON_SKILL = "depends_on_skill"


class JobMode(str, Enum):
    DELTA = "delta"
    BACKFILL = "backfill"


class MutationKind(IntEnum):
    MUTATION_APPEND_HISTORY = 0
    MUTATION_REINFORCE_ENTITY = 1
    MUTATION_CREATE_ENTITY = 2
    MUTATION_MERGE_ENTITIES = 3
    MUTATION_DEPRECATE_ENTITY = 4
    MUTATION_FORGET_MEMORY = 5


class PrivacyClass(str, Enum):
    PUBLIC = "public"
    PERSONAL = "personal"
    SENSITIVE = "sensitive"
    SECRET = "secret"


class ProposalPriority(str, Enum):
    BLOCKING = "blocking"
    QUEUED = "queued"


class ProposalStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    DECLINED = "declined"
    EXPIRED = "expired"
    SUPERSEDED = "superseded"


class RecoveryStatus(str, Enum):
    NOT_REQUIRED = "not_required"
    OPEN = "open"
    RESOLVED = "resolved"


class ResolutionType(str, Enum):
    NA = "na"
    APPROVED_ONCE = "approved_once"
    APPROVED_ALWAYS = "approved_always"
    SWITCHED_WORKSPACE = "switched_workspace"
    DENIED = "denied"


class ReversibilityClass(str, Enum):
    REVERSIBILITY_INTERNAL = "reversible_internal"
    REVERSIBILITY_COMPENSABLE = "compensable_external"
    REVERSIBILITY_IRREVERSIBLE = "irreversible"


class RunStatus(str, Enum):
    STARTING = "starting"
    ACTIVE = "active"
    PAUSED = "paused"
    WAITING_FOR_TOOL = "waiting_for_tool"
    WAITING_FOR_PROPOSAL = "waiting_for_proposal"
    WAITING_FOR_RECOVERY = "waiting_for_recovery"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class ValidationOutcome(IntEnum):
    VALIDATION_APPROVED = 0
    VALIDATION_REQUIRES_CONFIRMATION = 1
    VALIDATION_MODIFIED = 2
    VALIDATION_REJECTED = 3


@dataclass
class ActionDescriptor:
    "Generated from Go governor.ActionDescriptor."
    CommandType: CommandType = ""
    Domain: str = ""
    ActorKind: str = ""
    SkillEntry: Optional[Any] = None
    ChatID: str = ""
    RuntimeSessionID: str = ""
    OwnerID: str = ""
    Tags: Dict[str, str] = field(default_factory=dict)
    Mutation: Optional[MutationDescriptor] = None


@dataclass
class AssistantMessageCompletedPayload:
    "Generated from Go schema.AssistantMessageCompletedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    chat_id: str = ""
    message_id: str = ""
    content: str = ""
    experience_mode: str = ""
    inbox_item_id: str = ""
    message_kind: str = ""


@dataclass
class AssistantMessagePartialPayload:
    "Generated from Go schema.AssistantMessagePartialPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    content: str = ""
    state: str = ""


@dataclass
class AssistantTokenDeltaPayload:
    "Generated from Go schema.AssistantTokenDeltaPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    delta: str = ""


@dataclass
class CapabilityDescriptor:
    "Generated from Go connectors.CapabilityDescriptor."
    name: str = ""
    input_schema: Any = None
    output_schema: Any = None
    side_effect_class: str = ""
    idempotency_class: str = ""
    reversibility: str = ""
    risk_hint: str = ""
    required_permissions: List[str] = field(default_factory=list)
    supports_dry_run: bool = False
    supports_retry: bool = False


@dataclass
class ContextReadAuditPayload:
    "Generated from Go schema.ContextReadAuditPayload."
    caller: str = ""
    purpose: str = ""
    scope: str = ""
    run_id: str = ""
    redactions: List[str] = field(default_factory=list)
    found: bool = False


@dataclass
class DegradationNotedPayload:
    "Generated from Go schema.DegradationNotedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    degradation_type: str = ""
    message: str = ""
    recovery_proposal_id: str = ""
    tool_name: str = ""
    failure_code: str = ""
    fallback_path: List[str] = field(default_factory=list)
    fallback_disposition: str = ""


@dataclass
class Event:
    "Generated from Go schema.Event."
    id: str = ""
    type: EventType = ""
    kind: EventKind = ""
    correlation_id: str = ""
    causal_parent: str = ""
    source_agent: AgentType = ""
    target_agent: AgentType = ""
    timestamp: str = ""
    payload: Any = None
    schema_version: str = ""
    seq: int = 0
    run_id: str = ""
    visibility: EventVisibility = ""


@dataclass
class EventEnvelope:
    "Generated from Go connectors.EventEnvelope."
    connector_instance_id: str = ""
    event_type: str = ""
    payload: Any = None
    provider_metadata: Any = None
    received_at: str = ""
    correlation_id: str = ""


@dataclass
class ExecutionOutcome:
    "Generated from Go schema.ExecutionOutcome."
    attempt_id: str = ""
    command_id: str = ""
    attempt_number: int = 0
    retry_of: str = ""
    command_type: CommandType = ""
    start_time: str = ""
    end_time: Optional[str] = None
    outcome: ExecutionOutcomeOutcome = ""
    failure_class: FailureClass = ""
    failure_reason: str = ""
    affected_entities: str = ""
    retryable: bool = False
    compensation_required: bool = False
    compensation_status: CompensationStatus = ""
    recovery_status: RecoveryStatus = ""
    proposal_id: str = ""
    run_id: str = ""
    runtime_session_id: str = ""
    correlation_id: str = ""
    parent_run_id: str = ""
    skill_ids: List[str] = field(default_factory=list)
    connector_ids: List[str] = field(default_factory=list)
    llm_provider: str = ""
    llm_model: str = ""
    llm_task_class: str = ""
    llm_complexity: str = ""
    workspace_id: str = ""
    boundary_crossing: bool = False
    approval_required: bool = False
    approval_outcome: ApprovalOutcome = ""
    artifact_id: str = ""


@dataclass
class GovernanceBlockedPayload:
    "Generated from Go schema.GovernanceBlockedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    tool_name: str = ""
    reason: str = ""
    outcome: str = ""
    proposal_id: str = ""


@dataclass
class InferenceDecisionTracePayload:
    "Generated from Go schema.InferenceDecisionTracePayload."
    run_id: str = ""
    runtime_session_id: str = ""
    trace_id: str = ""
    contract_version: str = ""
    focus_id: str = ""
    selected_goal_id: str = ""
    focus_reason: str = ""
    dominant_mode: str = ""
    submode_chain: List[str] = field(default_factory=list)
    invoked_subreasoners: List[str] = field(default_factory=list)
    pinned_subreasoners: List[str] = field(default_factory=list)
    suppressed_subreasoners: List[str] = field(default_factory=list)
    arbitration_notes: List[str] = field(default_factory=list)
    candidate_ids: List[str] = field(default_factory=list)
    candidate_id: str = ""
    candidate_type: str = ""
    candidate_score: float = 0.0
    threshold_band: str = ""
    governance_outcome: str = ""
    execution_action_type: str = ""
    execution_target: str = ""
    approval_requirement: str = ""
    trace_stage: str = ""
    target_capability: str = ""
    allowed_capabilities: List[str] = field(default_factory=list)
    plan_id: str = ""
    current_node_id: str = ""
    plan_status: str = ""
    checkpoint_refs: List[str] = field(default_factory=list)
    recovery_route: str = ""
    recovery_checkpoint_ref: str = ""
    execution_outcome_ref: str = ""
    executed_capability: str = ""
    executed_command_type: str = ""
    proposal_id: str = ""
    recovery_ref: str = ""
    resume_focus_id: str = ""
    reflection_trigger: str = ""
    reflection_ref: str = ""
    tags: Dict[str, str] = field(default_factory=dict)


@dataclass
class IntakeRecordRef:
    "Generated from Go schema.IntakeRecordRef."
    record_id: str = ""
    connector_id: str = ""
    source_id: str = ""
    cursor: str = ""
    fetched_at: str = ""


@dataclass
class InterruptAppliedPayload:
    "Generated from Go schema.InterruptAppliedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    interrupt_class: str = ""
    reason: str = ""
    outcome: str = ""


@dataclass
class InterruptRaisedPayload:
    "Generated from Go schema.InterruptRaisedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    interrupt_class: str = ""
    reason: str = ""
    source_channel: str = ""


@dataclass
class MessageClassifiedPayload:
    "Generated from Go schema.MessageClassifiedPayload."
    runtime_session_id: str = ""
    chat_id: str = ""
    inbox_item_id: str = ""
    queue_action: str = ""
    reason: str = ""
    confidence: float = 0.0


@dataclass
class MessageQueueActionPayload:
    "Generated from Go schema.MessageQueueActionPayload."
    runtime_session_id: str = ""
    chat_id: str = ""
    inbox_item_id: str = ""
    queue_action: str = ""
    reason: str = ""
    confidence: float = 0.0
    target_inbox_item_id: str = ""


@dataclass
class MessageReceivedPayload:
    "Generated from Go schema.MessageReceivedPayload."
    runtime_session_id: str = ""
    chat_id: str = ""
    inbox_item_id: str = ""
    message_id: str = ""
    source_channel: str = ""
    source_message_ref: str = ""
    content_len: int = 0
    queue_action: str = ""


@dataclass
class Proposal:
    "Generated from Go schema.Proposal."
    proposal_id: str = ""
    source_process: str = ""
    source_trigger: str = ""
    boundary_key: str = ""
    proposed_action: str = ""
    affected_entities: str = ""
    rationale: str = ""
    priority: ProposalPriority = ""
    status: ProposalStatus = ""
    created_at: str = ""
    expires_at: Optional[str] = None
    resolved_at: Optional[str] = None
    resolved_by: str = ""
    resolution_type: ResolutionType = ""
    resolution_note: str = ""


@dataclass
class ProposalResolvedPayload:
    "Generated from Go schema.ProposalResolvedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    proposal_id: str = ""
    status: str = ""
    resolved_by: str = ""
    note: str = ""


@dataclass
class ProposalWaitingPayload:
    "Generated from Go schema.ProposalWaitingPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    proposal_id: str = ""
    tool_name: str = ""
    arguments: Dict[str, Any] = field(default_factory=dict)
    reason: str = ""


@dataclass
class RecoveryRequiredPayload:
    "Generated from Go schema.RecoveryRequiredPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    proposal_id: str = ""
    recovery_route: str = ""
    checkpoint_ref: str = ""
    current_task: str = ""
    current_step: str = ""
    pending_blockers: List[str] = field(default_factory=list)
    resume_conditions: List[str] = field(default_factory=list)
    rollback_point: str = ""
    failure_reason: str = ""


@dataclass
class ResolutionResult:
    "Generated from Go schema.ResolutionResult."
    candidate_name: str = ""
    matched_id: str = ""
    matched_type: str = ""
    confidence: float = 0.0
    reason: str = ""
    ambiguous: bool = False
    possible_merge_ids: List[str] = field(default_factory=list)


@dataclass
class ResultEnvelope:
    "Generated from Go connectors.ResultEnvelope."
    status: str = ""
    output: Any = None
    error: str = ""
    retryable: bool = False
    connector_instance_id: str = ""
    capability: str = ""
    correlation_id: str = ""
    duration_ms: int = 0
    provider_metadata: Any = None


@dataclass
class RunCancelledPayload:
    "Generated from Go schema.RunCancelledPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    reason: str = ""


@dataclass
class RunCompletedPayload:
    "Generated from Go schema.RunCompletedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    chat_id: str = ""
    reply_len: int = 0
    tool_calls: int = 0
    duration_ms: int = 0
    final_message_id: str = ""


@dataclass
class RunFailedPayload:
    "Generated from Go schema.RunFailedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    error: str = ""
    duration_ms: int = 0


@dataclass
class RunPausedPayload:
    "Generated from Go schema.RunPausedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    reason: str = ""
    proposal_id: str = ""
    phase: str = ""


@dataclass
class RunPhaseChangedPayload:
    "Generated from Go schema.RunPhaseChangedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    phase: str = ""
    previous: str = ""
    checkpoint: str = ""


@dataclass
class RunResumedPayload:
    "Generated from Go schema.RunResumedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    proposal_id: str = ""
    phase: str = ""


@dataclass
class RunStartedPayload:
    "Generated from Go schema.RunStartedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    experience_mode: str = ""
    phase: str = ""


@dataclass
class SoftenedMutation:
    "Generated from Go governor.SoftenedMutation."
    kind: MutationKind = 0
    possible_merge_with: List[str] = field(default_factory=list)
    reason: str = ""


@dataclass
class ToolCallCompletedPayload:
    "Generated from Go schema.ToolCallCompletedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    call_id: str = ""
    tool_name: str = ""
    result: str = ""
    duration_ms: int = 0


@dataclass
class ToolCallFailedPayload:
    "Generated from Go schema.ToolCallFailedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    call_id: str = ""
    tool_name: str = ""
    error: str = ""
    duration_ms: int = 0


@dataclass
class ToolCallProgressPayload:
    "Generated from Go schema.ToolCallProgressPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    call_id: str = ""
    tool_name: str = ""
    stage: str = ""
    message: str = ""
    duration_ms: int = 0


@dataclass
class ToolCallStartedPayload:
    "Generated from Go schema.ToolCallStartedPayload."
    run_id: str = ""
    runtime_session_id: str = ""
    call_id: str = ""
    tool_name: str = ""


@dataclass
class ValidationResult:
    "Generated from Go governor.ValidationResult."
    Outcome: ValidationOutcome = 0
    Reason: str = ""
    ModifiedAction: str = ""
    Tier: GovernanceTier = ""


@dataclass
class MutationDescriptor:
    "Generated from Go governor.MutationDescriptor."
    Kind: MutationKind = 0
    TargetType: str = ""
    TargetEntity: str = ""
    CandidateRefs: List[str] = field(default_factory=list)
    SourceRecords: List[IntakeRecordRef] = field(default_factory=list)
    Trust: ContentTrust = ""
    PrivacyClass: PrivacyClass = ""
    Resolution: ResolutionResult = field(default_factory=ResolutionResult)
    Derivation: List[str] = field(default_factory=list)
    EstConfidence: float = 0.0
    JobMode: JobMode = ""
    Source: str = ""
    VaultPath: str = ""
